config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    #sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 # root to: "home#index"
  root 'products#index'
  get 'welcome/index', 'welcome#index'

  # Carts
  # create cart
  post 'add_to_cart', action: 'create', controller: 'carts'
  # get 'cart/:id',

  # Orders
  # create order
  get 'make_order', action: 'create', controller: 'orders'

  # resources
  resources :products
  resources :orders
  resources :carts  #This should not have been done, as only two resources are needed
  # i.e. 'index', 'create', 'update' and destroy..and all of these four are custom routes
  resources :reviews
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  #product_orders
  has_many :product_orders
  has_many :products, through: :product_orders
  # accepts_nested_attributes_for :product_orders

  #Validations
  #total bill is like grand total

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[show edit update destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
    authorize @orders
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    authorize @order
  end

  # GET /orders/new
  def new
    @auth_order = Order.new
    authorize @auth_order
    # @ordered = Cart.where(user_id: current_user.id, id:)
    @carts = Cart.where(user_id: current_user.id)
    @order = @carts
    # @order = Cart.where(user_id: current_user.id)
    # authorize @order    # it is calling carts#new    !!!!!!!!!!!!!
  end

  # GET /orders/1/edit
  def edit
    authorize @order
  end

  # POST /orders
  # POST /orders.json
  def create
    # @order = Order.new(order_params)
    @order = OrderServices.build_order
    OrderServices.evaluate_order(current_user)
    authorize @order
    Order.transaction do
      @flag = OrderServices.create_order
      if @flag == true
        OrderServices.evaluate_product_order_and_clear_cart
        redirect_to products_path, notice: 'Order has been successfully placed'
      else
        render :new, notice: 'errors'
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    authorize @order
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    authorize @order
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def order_params
    params.fetch(:order, {})
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%#= form_with(model: order, local: true) do |form| %>
  <!-- <%# if order.errors.any? %>
    <div id="error_explanation">
      <h2><%#= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <%#order.errors.full_messages.each do |message| %>
        <li><%#= message %></li>
      <%# end %>
      </ul>
    </div>
  <%# end %> -->


  <table width="120%", style="font-size:15px;line-height:19px;">
    <thead>
      <tr>
        <th>Item Name</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Discount</th>
        <th>Total Price</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  <!-- To show price of each product, it's quantity, discount, and total amount here -->
    <tbody>
      <% @order.each do |cart| %>
        <tr>
          <td><%= cart.product.name %></td>
          <td><%= cart.product.price %></td>
          <td><%= cart.quantity %></td>
          <td><%= cart.product.discount %></td>
          <td><%= total = (cart.product.price * cart.product.quantity) - cart.product.discount %></td>
          <td><%= link_to 'Show', cart %></td>
          <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
          <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

<!-- Bugs here, as the data is being shown from the carts table, so it can be destroyed here! To handle it -->


<%= link_to '<button type="button">Place Order</button>'.html_safe, make_order_path %>

<!-- Go Back here for editing the order/cart -->


  <!-- <div class="actions">
    <%#= form.submit %>
  </div> -->
<%# end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>
<br>
<%= link_to 'Edit', carts_path %>

<%= link_to 'Back', carts_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>