config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    #sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 # root to: "home#index"
  root 'products#index'
  get 'welcome/index', 'welcome#index'

  # Carts
  # create cart
  post 'add_to_cart', action: 'create', controller: 'carts'
  # get 'cart/:id',

  # Orders
  # create order
  get 'make_order', action: 'create', controller: 'orders'

  # resources
  resources :products
  resources :orders
  resources :carts  #This should not have been done, as only two resources are needed
  # i.e. 'index', 'create', 'update' and destroy..and all of these four are custom routes
  resources :reviews
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :product
  belongs_to :user

  validates :quantity, presence: true
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[show edit update destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.new
    authorize @carts, :user_logged_in?
    @carts = Cart.where(user_id: current_user.id)
    @carts.each do |c|
      if c.product.flag == false
        c.destroy
      else
        if c.quantity > c.product.quantity
          c.quantity = c.product.quantity
          c.update(cart_params)
        end
      end
    end
    authorize @carts
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    authorize @cart
  end

  # GET /carts/new
  def new
    @cart = Cart.new
    authorize @cart
  end

  # GET /carts/1/edit
  def edit
    authorize @cart
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = CartServices.build_cart(cart_params)
    authorize @cart
    @notice = CartServices.verify_quantity_in_create
    if @notice == 'update'
      update
    elsif @notice == 'no error found'
      @notice = CartServices.create_cart
      render_alert(@notice)
    else
      render_alert(@notice)
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  # it updates the cart only when called through the create controller
  def update
    @cart = CartServices.get_cart
    authorize @cart
    @notice = CartServices.verify_quantity_in_update
    if @notice == 'product_quantity' || @notice == 'update'
      @notice = CartServices.update_cart
      render_alert(@notice)
    else
      render_alert(@notice)
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    authorize @cart
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cart
    @cart = Cart.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cart_params
    params.fetch(:cart, {}) # it is a hash for avoiding null array
    params.permit(:product_id, :quantity).merge(user: current_user)
  end

  def render_alert(notice)
    redirect_to products_path, notice: notice
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<h1>Carts</h1>

<!-- <table cellpadding="pixels"cellspacing="pixels"> -->
<table width="120%", style="font-size:15px;line-height:19px;">
  <thead>
    <tr>
      <th>Customer Name</th>
      <th>Item name</th>
      <th>Quantity</th>
      <th>Price Per Item</th>
      <th>Total Price</th>
      <th>Discount</th>
      <th>Final Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>
<!-- To show price of each product, it's quantity, discount, and total amount here -->
  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= "#{current_user.first_name}  #{current_user.last_name}" %></td>
        <td><%= cart.product.name %></td>
        <td><%= cart.quantity %></td>
        <td><%= cart.product.price %></td>
        <td><%= totalPrice = cart.product.price * cart.product.quantity %></td>
        <td><%= cart.product.discount %></td>
        <td><%= total = totalPrice - cart.product.discount %></td>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<!-- <%# if @carts.len %> -->
<%= link_to 'Checkout', new_order_path(cart: @cart) %>
<br>
<%= link_to 'New Cart', new_cart_path %>

<%= link_to 'Back', root_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>