config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    #sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 # root to: "home#index"
  root 'products#index'
  get 'welcome/index', 'welcome#index'

  # Carts
  # create cart
  post 'add_to_cart', action: 'create', controller: 'carts'
  # get 'cart/:id',

  # Orders
  # create order
  get 'make_order', action: 'create', controller: 'orders'

  # resources
  resources :products
  resources :orders
  resources :carts  #This should not have been done, as only two resources are needed
  # i.e. 'index', 'create', 'update' and destroy..and all of these four are custom routes
  resources :reviews
end

app/models/product.rb
class Product < ApplicationRecord
  # for user stamps
  audited
  # product_orders
  has_many :product_orders, dependent: :destroy
  has_many :orders, through: :product_orders
  # images
  has_many :images, as: :imageable, dependent: :destroy
  # reviews
  has_many :reviews, dependent: :destroy
  # rating
  has_many :ratings, as: :rated, dependent: :destroy
  # cart
  has_many :carts, dependent: :destroy

  # Validations
  before_validation :checkQuantity, on: %i[create update save] # to make it after validation
  # before_validation :set_delete_by_user, on: [:destroy]
  validates :name, :quantity, :cost, :price, :discount, presence: true

  validates :flag, inclusion: { in: [true, false] } # to make this too after validation and function call
  validates :flag, exclusion: { in: [nil] } # to make this too after validation and function call

  scope :flagged, -> { where(flag: true) }
  scope :unflagged, -> { where(flag: false) }
  def flagged?
    flag == true
  end

  private

  def checkQuantity
    self.flag = quantity != 0
  end
  # def set_assigned_by_user
  #   self.added_by_user_id=current_user.id
  # end
  # def set_delete_by_user
  #   self.delete_by_user_id=current_user.id
  # end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.flagged
    authorize @products
    @falseproducts = Product.unflagged
  end

  # GET /products/1
  # GET /products/1.json
  def show
    authorize @product
    @images = Image.where(imageable_id: @product.id)
    @reviews = Review.where(product_id: @product.id)
  end

  # GET /products/new
  def new
    @product = Product.new
    authorize @product
  end

  # GET /products/1/edit
  def edit
    authorize @product
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    authorize @product
    if params[:images].nil?
      @product.errors.add('Image Error:', 'No Image selected')
      render_alert('image error')
    else
      counter = params[:images]['image'].count
      if counter > 5
        @image_notice = 'Five images added, you cannot upload more than five images'
      end
      if @image_notice.nil?
        if @product.save
          save_images
          render_alert('success')
        else
          render_alert('errors')
        end
      else
        @product.errors.add('Image Error:', 'Five images added, you cannot upload more than five images')
        render_alert('image errors')
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    authorize @product
    @product.added_by_user_id = current_user.id
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    authorize @product
    if @product.flagged?
      set_params
      @product.save
    else
      @product.destroy
    end
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  rescue StandardError => ex
    redirect_to action: 'index', notice: 'Product not found.'
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    # params.fetch(:product, {})
    params.require(:product).permit(:name, :description, :price, :cost, :discount, :quantity, images_attributes: [:image])
  end

  def image_params
    params.require(:product).permit(:image)
  end

  def set_params
    @product.quantity = 0
  end

  def save_images
    params[:images]['image'].each do |a|
      @image = @product.images.create!(image: a)
    end
  end

  def render_alert(flag)
    respond_to do |format|
      if flag == 'success'
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_allreview.html.erb
<div class = 'col-sm-4 col-md-4 append-div' >
 <% @reviews.each do |comment| %>
   <div class = 'container'  id='comment-parent' >
       <div class = "card comment-parent-<%= comment.id %>">
         <div class = 'card-body'>
             <!-- <div class = 'row'> -->
                 <!-- <div class = 'col-md-2'>
                     <%#= image_tag('dummy-profile-img.jpg', size: "72x72", class: 'img img-rounded img-fluid') %>
                 </div> -->
                 <div class = 'col-md-10'>
                     <p>
                       <a class = 'float-left' ><strong><%= comment.user.name %></strong></a>
                       <span class = 'float-right'><i class = 'text-warning fa fa-star'></i></span>
                       <span class = 'float-right'><i class = 'text-warning fa fa-star'></i></span>
                       <span class = 'float-right'><i class = 'text-warning fa fa-star'></i></span>
                       <span class = 'float-right'><i class = 'text-warning fa fa-star'></i></span>
                     </p>
                     <!-- <div class = 'clearfix'></div>
                     <p><%= comment.revcontent %></p>
                     <%# if comment.comment_id.nil? %>
                       <div id='reply-area'>
                         <button class='show-reply'> Reply</button>
                         <div class='reply-div'>
                           <%#= render partial: 'comments/reply', locals: {comment_id: comment.id, bug_id: @bug.id} %>
                         </div>
                       </div> -->

                    <%# end %>
                 </div>
             <!-- </div> -->
             <!-- <div class = 'card card-inner reply-add'></div>
             <%# if !comment.reply.nil? %>
               <div class = 'card card-inner reply-add'>
                     <div class = 'card-body'>
                         <!-- <div class = 'row'>
                           <!-- <div class = 'col-md-2'>
                                 <%#= image_tag('dummy-profile-img.jpg', size: '72x72', class: 'img img-rounded img-fluid') %>
                             </div> -->
                             <!-- <div class = 'col-md-10' id="reply-parent-<%= comment.id %>">
                                 <p><strong><%#= comment.reply.user.name %></strong></p>
                                 <p><%#= comment.reply.comment_detail %></p>
                             </div> -->
                         <!-- </div> -->
                     <!-- </div> -->
                 <!-- </div> -->
             <%# end %>
         <!-- </div> -->
     </div>
   </div>
 <% end %>
</div>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <p>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </p>

    <p>
      <%= form.label :description %><br>
      <%= form.text_field :description %>
    </p>

    <p>
      <%= form.label :quantity %>
      <%= form.text_field :quantity %>
    </p>

      <p>
        <%= form.label :cost %>
        <%= form.text_field :cost %>
      </p>

        <p>
          <%= form.label :price %>
          <%= form.text_field :price %>
        </p>

        <p>
          <%= form.label :discount %>
          <%= form.text_field :discount, value: 0 %>
        </p>

        <div>
          <%= form.label :image %>
          <%= form.file_field :image, multiple: true, name: "images[image][]" %>
        </div>
    <br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<!--<p id="notice"><%= notice %></p>-->

<h1>Products</h1>
<a href="#" onclick="this.style.backgroundColor='#990000'">Paint it red</a>

<a href="#" onclick="this.style.backgroundColor='#009900';this.style.color='#FFFFFF';">Paint it green</a>

<br>
<a href="#" onclick="paintIt(this, '#990000')">Paint it red</a>

<table width="120%", style="font-size:15px;line-height:19px;">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Quantity</th>
      <th>Price</th>
      <!-- <th>Cost</th> -->
      <th>Discount</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
    <%# if policy(@product).index? %>
        <tr>
          <td><%= product.name %></td>
          <td><%= product.description %></td>
          <td><%= product.quantity %></td>
          <td><%= product.price %></td>
          <td><%= product.discount %></td>
          <td><%= link_to 'Show', product %></td>
          <td><%= link_to 'Edit', edit_product_path(product) %></td>
          <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>

          <%= form_tag({controller: "carts", action: "create"}, method: "post") do %>
              <td><%= number_field_tag(:quantity) %></td>
              <td><%= hidden_field_tag 'product_id', product.id  %></td>
              <td><%= submit_tag("Add to Cart") %></td>
          <% end %>

        </tr>
      <%# end %>
      <!-- , add_to_cart_path(:product_id => product.id , :quantity => "quantity[{:value=>1}]")-->
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Product', new_product_path %>
<br>
<%= link_to 'Show Cart', carts_path %>
<br>
<%# if policy(:product).update? %>
<% if policy(:product).user_logged_in? %>
<%# if user_signed_in? %>

  <% if policy(:product).update? %>
  <table width="120%", style="font-size:15px;line-height:19px;">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Quantity</th>
        <th>Price</th>
        <th>Cost</th>
        <th>Discount</th>
        <th>Flag</th>
        <th colspan="4"></th>
      </tr>
    </thead>

    <tbody>
      <% @falseproducts.each do |product| %>
      <% if policy(:product).edit? %>
          <tr>
            <td><%= product.name %></td>
            <td><%= product.description %></td>
            <td><%= product.quantity %></td>
            <td><%= product.price %></td>
            <td><%= product.cost %></td>
            <td><%= product.discount %></td>
            <td><%= product.flag %></td>
            <td><%= link_to 'Show', product %></td>
            <td><%= link_to 'Edit', edit_product_path(product) %></td>
            <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <td><%= link_to 'Add to Cart', add_to_cart_path(:product_id => product.id) %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
    <%= link_to "Edit post", carts_path %>
    <% end %>
<% end %>

app/views/products/new.html.erb
<h1>Order Details</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!-- For showing reviews -->
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!--
Author : Maniruzzaman Akash
Email  : manirujjamanakash@gmail.com
-->
<!--To Work with icons-->
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">


<div class="container">
  <div class="post-comments">
    <p>
      <h3>
      User:
      <i><%= @product.audits.last.user.first_name%> </i>
    </h3>
    </p>
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<p>
  <strong>price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>cost:</strong>
  <%= @product.cost %>
</p>

<p>
  <%#puts("data"*50)%>
    <%#puts(@image)%>
<%#= image_tag @image1.image.url%>
<%# for image in @images do %>
    <%#= image_tag image, size: "150x150" %>
<%# end %>
<% @images.each do |p| %>
  <%= image_tag p.image_url, size: "150x150"  %>
  <%#= link_to "Edit Attachment", edit_post_attachment_path(p) %>
<% end %>
</p>

<br>
<br>

<%= form_tag({controller: "reviews", action: "create"}, method: "post", remote: :true) do %>
    <!-- <%#= label_tag(:q, "Search for:") %> -->

    <div class="form-group">
      <%= label_tag(:your_comment)%>
      <!-- <%#= class="form-control" rows="3" text_area_tag(:review)%> -->
      <br>
      <%= text_area_tag(:revcontent)%>
      <%= hidden_field_tag 'product_id', @product.id  %>
    </div>
    <%= submit_tag("Post") %>

<% end %>
<!-- <button onclick="toggle_rev_div('reviewsection');"> Click Here </button> -->
<br>
<div class = "above-append">

  <% @reviews.reverse.each do |review| %>
    <% if review.comment_id.nil? %>
      <div class = "append<%= review.product_id %>">
      <%= render review %>
    <% end %>
  <% end %>
    <%#= render @reviews_replies.reverse %>
</div>

<!-- saving using ajax -->
<!-- <textarea name="revcontent" id="revcontent" cols="20" rows="5"></textarea>
<input type="hidden" id="product_id" name="product_id" value=<%= @product.id%>>
<button name="add_review" id="add_review">Post</button> -->

  </div>
</div>
<br>


<!--
<div class="container" id="reviewsection">
	<h2 class="text-center">Comments and Reviews</h2>

	<div class="card">
	    <div class="card-body">
	        <div class="row">
        	    <div class="col-md-2">
        	        <img src="https://image.ibb.co/jw55Ex/def_face.jpg" class="img img-rounded img-fluid"/>
        	        <p class="text-secondary text-center">15 Minutes Ago</p>
        	    </div>
        	    <div class="col-md-10">
        	        <p>
        	            <a class="float-left" href="https://maniruzzaman-akash.blogspot.com/p/contact.html"><strong>Maniruzzaman Akash</strong></a>
        	            <span class="float-right"><i class="text-warning fa fa-star"></i></span>
                        <span class="float-right"><i class="text-warning fa fa-star"></i></span>
        	            <span class="float-right"><i class="text-warning fa fa-star"></i></span>
        	            <span class="float-right"><i class="text-warning fa fa-star"></i></span>

        	       </p>
        	       <div class="clearfix"></div>
        	        <p>Lorem Ipsum is simply dummy text of the pr make  but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
        	        <p>
        	            <a class="float-right btn btn-outline-primary ml-2"> <i class="fa fa-reply"></i> Reply</a>
        	            <a class="float-right btn text-white btn-danger"> <i class="fa fa-heart"></i> Like</a>
        	       </p>
        	    </div>
	        </div>
	        	<div class="card card-inner">
            	    <div class="card-body">
            	        <div class="row">
                    	    <div class="col-md-2">
                    	        <img src="https://image.ibb.co/jw55Ex/def_face.jpg" class="img img-rounded img-fluid"/>
                    	        <p class="text-secondary text-center">15 Minutes Ago</p>
                    	    </div>
                    	    <div class="col-md-10">
                    	        <p><a href="https://maniruzzaman-akash.blogspot.com/p/contact.html"><strong>Maniruzzaman Akash</strong></a></p>
                    	        <p>Lorem Ipsum is simply dummy text of the pr make  but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
                    	        <p>
                    	            <a class="float-right btn btn-outline-primary ml-2">  <i class="fa fa-reply"></i> Reply</a>
                    	            <a class="float-right btn text-white btn-danger"> <i class="fa fa-heart"></i> Like</a>
                    	       </p>
                    	    </div>
            	        </div>
            	    </div>
	            </div>
	    </div>
	</div>
</div>
 -->


<br>
<br>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>